dist: bionic

language: go
go:
  - "1.14"
  - master

install:
  - go get -v -t -d ./...

script:
  - go test -race -coverprofile=codecov.out -covermode=atomic

after_script:
  - bash <(curl -s https://codecov.io/bash) -f codecov.out
