name: Go1.13
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Codecov
      uses: codecov/codecov-action@v1.0.4
      with:
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: coverage.txt
